### PR TITLE
chore: ADD nvmrc

### PR DESCRIPTION
**Pull request by whutchinson98**
add nvmrc so you can just run `nvm use` before building to ensure you are on the correct node version

Feel free to close if you don't think this is useful.

### CODE REVIEW

**Comment by chase** [comment]
What part is is for? https://github.com/coparse-inc/electron-libreoffice/blob/main/src/electron/.nvmrc

**Comment by whutchinson98** [comment]
> 

From the root of the repo it will allow you to run `nvm use` then `scripts/e build`

**Comment by chase** [comment]
> > 
> 
> From the root of the repo it will allow you to run `nvm use` then `scripts/e build`

If that's the case, then it should be 14 just like in `src/electron`

**Comment by whutchinson98** [comment]
> > > 
> > 
> > 
> > From the root of the repo it will allow you to run `nvm use` then `scripts/e build`
> 
> If that's the case, then it should be 14 just like in `src/electron`

`Prerequisites.md` references necessary node version as 16 though

**Comment by chase** [comment]
Sure, looks like we build in CI with v16 too.

**Review by chase — APPROVED** [review]

**Pull request merged**
