### PR TITLE
MACRO-1216 feat: Add in cmd/ctrl+scroll to zoom and trackpad pinching to zoom

### PR DESCRIPTION
**Pull request by whutchinson98**
https://github.com/coparse-inc/electron-libreoffice/assets/6412775/dfe0ebef-458c-45d1-b9a9-3fbd1c8b598a

Updated video showing that the refresh size is called (this is called from `document_size_changed` event)

https://github.com/coparse-inc/electron-libreoffice/assets/6412775/c88a6bef-b5c0-46c3-882b-bf26f9c2e35a

### CODE REVIEW

**Comment by chase** [comment]
Good start.

It looks like it isn't do a paint when zooming in for some cases, aka, it remains blurry.

Also, you should emit the appropriate events so that the JS-side of things knows things have been resized.

**Comment by whutchinson98** [comment]
> Good start.
> 
> It looks like it isn't do a paint when zooming in for some cases, aka, it remains blurry.
> 
> Also, you should emit the appropriate events so that the JS-side of things knows things have been resized.



> Good start.
> 
> It looks like it isn't do a paint when zooming in for some cases, aka, it remains blurry.
> 
> Also, you should emit the appropriate events so that the JS-side of things knows things have been resized.

Do you know the events? I am calling the SetZoom under the hood which is the same way we zoom in js land as that is exposed in `libreoffice.d.ts` so I assumed all necessary events would be handled

**Comment by chase** [comment]
> > Good start.
> > It looks like it isn't do a paint when zooming in for some cases, aka, it remains blurry.
> > Also, you should emit the appropriate events so that the JS-side of things knows things have been resized.
> 
> > Good start.
> > It looks like it isn't do a paint when zooming in for some cases, aka, it remains blurry.
> > Also, you should emit the appropriate events so that the JS-side of things knows things have been resized.
> 
> Do you know the events? I am calling the SetZoom under the hood which is the same way we zoom in js land as that is exposed in `libreoffice.d.ts` so I assumed all necessary events would be handled

Look how zoom is handled in QA: https://github.com/coparse-inc/electron-libreoffice/blob/main/qa/wrapper.js#L140

What else causes the size to refresh? 
https://github.com/coparse-inc/electron-libreoffice/blob/main/qa/wrapper.js#L158

**Comment by whutchinson98** [comment]
> > > Good start.
> > > It looks like it isn't do a paint when zooming in for some cases, aka, it remains blurry.
> > > Also, you should emit the appropriate events so that the JS-side of things knows things have been resized.
> > 
> > 
> > > Good start.
> > > It looks like it isn't do a paint when zooming in for some cases, aka, it remains blurry.
> > > Also, you should emit the appropriate events so that the JS-side of things knows things have been resized.
> > 
> > 
> > Do you know the events? I am calling the SetZoom under the hood which is the same way we zoom in js land as that is exposed in `libreoffice.d.ts` so I assumed all necessary events would be handled
> 
> Look how zoom is handled in QA: https://github.com/coparse-inc/electron-libreoffice/blob/main/qa/wrapper.js#L140
> 
> What else causes the size to refresh? https://github.com/coparse-inc/electron-libreoffice/blob/main/qa/wrapper.js#L158

Ohhh I see. I'll emit the `document_size_changed` event after zooming.

**Comment by chase** [comment]
> I talked with @awallace and it seems like to keep our magic 8px clamping for ensuring the resolution looks smooth we may have to do some work on the JS side of things as well.

Not quite. The clamping should really be done inside of C++ instead of JS so that all sources of zoom/scaling are consistent.

The tile size is based on scaling which is done in the tile buffer: https://github.com/coparse-inc/electron-libreoffice/blob/main/src/electron/office/lok_tilebuffer.cc#L58-L71

Try clamping there instead.

---

I don't have the time to debug for you, but be aware that you can initialize the default value in the call itself and don't have to worry about copy vs. move semantics: `Emit('document_size_changed', {})`.

Step through a debugger to figure out if the issue is what you think it is. Also look at how other parts of that class interact with the event bus.

**Review by chase — DISMISSED** [review]
See comments

**Comment by skececi** [comment]
Just watched the video, I think i'd have to see it live to determine if we're good to go UX wise. Or i can pull down and try it out. But at first glance looks smooth!

A few noticable issues:
- The cursor position flies around while zooming (afaik this will be addressed in the monorepo?)
- When zooming out, the edge of the doc is cut off and remains the grey background. Couldn't clearly tell what was going on in the background here.

**Comment by whutchinson98** [comment]
> Just watched the video, I think i'd have to see it live to determine if we're good to go UX wise. Or i can pull down and try it out. But at first glance looks smooth!
> 
> A few noticable issues:
> 
> * The cursor position flies around while zooming (afaik this will be addressed in the monorepo?)
> * When zooming out, the edge of the doc is cut off and remains the grey background. Couldn't clearly tell what was going on in the background here.

- I can do a live demo with you to help see if everything is good or not for sure. 
- The cursor position will be addressed in the monorepo.
- If you are referring to that massive snap back I did to go to minimum zoom I think what was happening is that I zoomed so fast since it was with pinch I was able to have the re-painting of tiles paused for longer

**Pull request closed without merging**
